### ISSUE TITLE
os_input_string not getting backspaces

### ISSUE THREAD

**Issue by SuperFola** [mig-hub/mikeOS#2]
hi !

I am playing with your code, and i noticed that, in the shell, the backspace is not working everytime : when the line is empty, it is fine, but it you type anything and then try to use backspace, it freeze everything. i thought it was coming from os_get_cursor_pos but it does not, after having investigate a bit.

literally, i find it stopping where i put the comment : 
```asm
.backspace:
    cmp cx, 0           ; Backspace at start of string?
    je .more            ; Ignore it if so

    call scp_get_cursor_pos  ; Backspace at start of screen line?
    cmp dl, 0
    je .backspace_linestart
                                                         ; ------>>>>> here
    pusha
    mov ah, 0xE         ; If not, write space and move cursor back
    mov al, 8
    int 0x10            ; Backspace twice, to clear space
    mov al, 32
    int 10h
    mov al, 8
    int 0x10
    popa

    dec di          ; Character position will be overwritten by new
                    ; character or terminator at end

    dec cx          ; Step back counter

    jmp .more
```

**Comment by SuperFola** [comment]
it is me again, i think that it is because of `call scp_get_cursor_pos  ; Backspace at start of screen line?`. if i comment it (along with the `cmp dl, 0` and `je .backspace_linestart`) it is fine for me !

**Comment by mikegonta** [comment]
`scp_get_cursor_pos` is not in the original MikeOS 4.5 which works fine with respect to your issue.
If you have modified the code you should fork the original and present your issues there.

**Comment by SuperFola** [comment]
i did not rewrite the code, only changing naming convention for the moment

**Comment by ghost** [comment]
Just tested and backspace seems to work fine in the official build. I've never had any problems with it. Are you sure it isn't something you've changed? Perhaps you could clarify what the problem is?

**Comment by mig-hub** [comment]
Hello @Loodoor 
I am not the author of this project.
Like said in the title of the repo, this is only a mirror because the original is not available on Github.

The author is actually Mike Saunders and here is the project page:
[MikeOS](http://mikeos.sourceforge.net/)

He obviously knows the project inside out and will most likely be able to answer your questions.

**Comment by SuperFola** [comment]
Fixed, i was using a register i shouldn't have x)
