### ISSUE TITLE
mikeOS has a live floppy! Could be a part of BIOS image ;) 

### ISSUE THREAD

**Issue by informer2016** [mig-hub/mikeOS#4]
**dear @mig-hub **, Thank you very much for the mikeOS !
I tested your OS inside the Virtual Box --- mikeOS is amazing! And, most importantly, it has a live floppy! :+1: Even today the floppies are still being used, for example - as virtual floppies inside the coreboot open source BIOS. Just imagine: your wonderful OS could be a part of someone's BIOS build! _(for coreboot supported motherboard, maybe you have or could get one - see https://www.coreboot.org/Supported_Motherboards )_

If you already have a coreboot-supported motherboard, or a real chance to get one, - wouldn't it be cool to be able to launch your own OS straight from the BIOS chip? ;) With one simple command its possible to add any floppy to coreboot BIOS build - and then you see it as a boot entry. Multiple floppies could be added this way _(as long as you have enough space left inside the BIOS flash chip, luckily LZMA compression could be used for the stored floppies to reduce their occupied size)_

I wish you good luck in your project, mikeOS is awesome

**Comment by mig-hub** [comment]
Hello @informer2016 , thank you for these kind words, MikeOS is indead awsome. But I am actually not the right person to thank. My repository is only a mirror to make it available on Github. MikeOS was actually created by [Mike Saunders](mailto:okachi@gmail.com) and I'm sure he'll be happy to hear the nice thing you have to say about his work.

The official page for the project is [mikeos.sourceforge.net](http://mikeos.sourceforge.net/).

Cheers,
Mig

**Comment by informer2016** [comment]
@mig-hub Hi there Mig! To let you know, there as a TachyonOS fork of MikeOS at Github . Please take a look if you are interested - https://github.com/ZeroKelvinKeyboard/TachyonOS

**Comment by voidnull000** [comment]
> @mig-hub commented on 3 Jan
> @informer2016 commented 14 days ago

Necro-posting much?
(I don't like that term, fun fact.)
