### ISSUE TITLE
Is this mike?

### ISSUE THREAD

**Issue by trevortomesh** [mig-hub/mikeOS#5]
Hey, Mike... is this your account or is this just a clone?

**Comment by mig-hub** [comment]
Confusingly, my name is Mickael, but I am probably not the Mike you are looking for ;-)
I am not Mike Saunders, the creator of MikeOS.

This repository is just a clone to make MikeOS available on Github.

**Comment by trevortomesh** [comment]
Gotcha. Thanks. :-D
