### ISSUE TITLE
Adding Filesystem to FLP File

### ISSUE THREAD

**Issue by ktwrd** [mig-hub/mikeOS#6]
When I use the run command, everything BUT adding the bootloader to the floppy file.
<img width="408" alt="screen shot 2018-04-10 at 9 20 36 am" src="https://user-images.githubusercontent.com/26735262/38531017-80764962-3ca0-11e8-86c7-5fd73e88f4d0.png">

Here is the code I have for the build script
<img width="788" alt="screen shot 2018-04-10 at 9 20 52 am" src="https://user-images.githubusercontent.com/26735262/38531030-8c4d655e-3ca0-11e8-8127-9cc9757b8d55.png">

**Comment by AtieP** [comment]
noxfer is invalid, that's why
did you fix it before i came?

**Comment by ghost** [comment]
This was a bug in the OSX build script a while ago that has since been fixed. `status=noxfer` is a valid option on Linux only. This can be closed.

**Comment by mig-hub** [comment]
Hello guys,

Thank you very much for reporting issues and sending push requests. Unfortunately this git repository is only a mirror and I am not the author.

The author is Mike Saunders and here is the website: [MikeOS](http://mikeos.sourceforge.net/)
